services:
  backend:
    build:
      context: ./backend/go
    volumes:
      - ./backend/go:/app
    ports:
      - "8082:8082"
    environment:
      - JWT_KEY=secret
    command: [ "/go/bin/air" ]

  ui-web:
    build:
      context: ./frontend/svelte
    volumes:
      - ./frontend/svelte:/app
      - /app/node_modules
    ports:
      - "5175:5175"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PUBLIC_FIREBASE_API_KEY=${PUBLIC_FIREBASE_API_KEY:-}
      - PUBLIC_FIREBASE_AUTH_DOMAIN=${PUBLIC_FIREBASE_AUTH_DOMAIN:-}
      - PUBLIC_FIREBASE_PROJECT_ID=${PUBLIC_FIREBASE_PROJECT_ID:-}
      - PUBLIC_FIREBASE_STORAGE_BUCKET=${PUBLIC_FIREBASE_STORAGE_BUCKET:-}
      - PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${PUBLIC_FIREBASE_MESSAGING_SENDER_ID:-}
      - PUBLIC_FIREBASE_APP_ID=${PUBLIC_FIREBASE_APP_ID:-}
      - PUBLIC_FIREBASE_MEASUREMENT_ID=${PUBLIC_FIREBASE_MEASUREMENT_ID:-}
    depends_on:
      - backend
