version: '3.8'

services:

  backend:
    build:
      context: ./backend/go
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/go:/app
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=secret
    command: ["/go/bin/air"]

  ui-web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongo-data:
