services:
  backend:
    build:
      context: ./backend/go
    env_file:
      - ./backend/go/.env
    volumes:
      - ./backend/go:/app
    ports:
      - "8082:8082"
    command: ["/go/bin/air"]

  frontend:
    build:
      context: ./frontend/svelte
    volumes:
      - ./frontend/svelte:/app
      - /app/node_modules
    ports:
      - "5175:5175"
    depends_on:
      - backend