services:
  backend:
    build:
      context: ./backend/go
    volumes:
      - ./backend/go:/app
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=secret
    command: ["/go/bin/air"]

  ui-web:
    build:
      context: ./frontend/web
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
